export const actionTypes = {
  ADD_ELEMENT: "ADD_ELEMENT",
  DELETE_ELEMENT: "DELETE_ELEMENT",
  CHECK_WORD: "CHECK_WORD",
  SET_WORD: "SET_WORD",
  RESET_WORD: "RESET_WORD",
  INCREASE_SIZE: "INCREASE_SIZE",
  DECREASE_SIZE: "DECREASE_SIZE",
};
